"""Step 1: the context inventory.

A CONTEXT is a dict per scene with EVERYTHING the builder needs:
the paths of its 9 files and the precomputed metadata. It is the only
boundary with the data pipeline: if the context is complete, the rest
of the build is mechanical.

PREPARED, NOT RUN YET.
"""
import pandas as pd

from config import ASSETS, ASSETS_DIR, INVENTARIO


def load_contexts(limit: int | None = None) -> list[dict]:
    """One inventory row -> one context per scene."""
    df = pd.read_parquet(INVENTARIO)
    if limit:
        df = df.head(limit)

    contexts = []
    for _, row in df.iterrows():
        gid = row["granule_id"]
        ctx = {
            "id": gid,
            # paths of the 9 assets, already generated by the pipeline
            "paths": {name: ASSETS_DIR / gid / name for name in ASSETS},
            # metadata per namespace (the keys are consumed by the extensions)
            "detection": {
                "n_imeo": row["n_imeo"], "n_cm": row["n_cm"],
                "imeo_ids": row["imeo_ids"], "cm_ids": row["cm_ids"],
                "imeo_flux": row["imeo_flux"], "cm_flux": row["cm_flux"],
                "sector": row["sector"],
            },
            "sensor": {
                "sza_mean": row["sza_mean"], "vza_mean": row["vza_mean"],
                "amf_mean": row["amf_mean"],
                "sun_azimuth_mean": row["sun_azimuth_mean"],
                "sensor_azimuth_mean": row["sensor_azimuth_mean"],
            },
            "spatial": {
                "bbox_west": row["bbox_west"], "bbox_south": row["bbox_south"],
                "bbox_east": row["bbox_east"], "bbox_north": row["bbox_north"],
            },
            "site": {"country": row["country"]},
            "meteo": {
                "wind_u": row["wind_u"], "wind_v": row["wind_v"],
                "wind_speed": row["wind_speed"],
            },
        }
        contexts.append(ctx)
    return contexts


def check_context(ctx: dict) -> list[str]:
    """Fail early: lists the assets missing on disk for one scene."""
    return [str(p) for p in ctx["paths"].values() if not p.exists()]
